### ISSUE TITLE
Plural for URI

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#10]
From TAPICC created by [ysavourel](https://github.com/ysavourel) : GALAglobal/TAPICC#13  

One suggestion: Using the plural forms for the URIs:

```
/jobs
/jobs/{id}
/jobs/{jobId}/assets
/jobs/{jobId}/assets/{assetId}
etc.
```

It feels more intuitive (`GET /jobs` lists all the jobs, `GET /jobs/123` gets the job 123 among all jobs)

**Comment by Alino** [comment]
I think this should be implemented, because top tech companies are using this approach.

**Comment by ysavourel** [comment]
+1 for plural as it seems to be the most common convention across many APIs.

**Comment by Alino** [comment]
closed with commit https://github.com/GALAglobal/TAPICC-API-implementation/commit/db905d532d7fdb9b5528920ad0b48596e9c321ee
and swagger definition was changed accordingly
