### ISSUE TITLE
XLIFF extraction and merging open source tool

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#12]
From TAPICC created by [Alino](https://github.com/Alino) : GALAglobal/TAPICC#19  

Are you aware of such tools? Which one do you think is the best?
If we want to enable the TAPICC API to do merging and extracting, I suggest that we should use external tool for this. My vision is that it should be a command line tool which could be run in linux terminal.
Something like [tikal](https://okapiframework.org/wiki/index.php?title=How_to_Extract_Text_for_Translation)

few related questions
1. What file types do we want to support?
2. What would be the workflow/steps when a user is supposed to perform an extract or merge?
3. Should this be a separate API endpoint, or should this happen in the background when a user uploads a file (Asset) to a Task?
4. What happens after the extraction is done? Are we saving the XLIFF or adding data to database?
5. What happens after the merge is done? Are we somehow manipulating the database or producing a file?

**Comment by Alino** [comment]
@DavidFatDavidF Hi David, if I understood correctly, you wanted to have some API endpoints for XLIFF extraction and merging. If that's correct, could you please explain how should the endpoints work?
Thank you

**Comment by rmraya** [comment]
There are many tools that can generate/merge XLIFF files. There is no way you can define a common API that integrates them all.

**Comment by ysavourel** [comment]
I agree with Rodolfo, I don't think the API should have such endpoints.

The example implementation can implement such process but that is something outside the API itself.

**Comment by Alino** [comment]
closing inactive issues
