### ISSUE TITLE
User data model schema

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#13]
What information should we keep regarding user?
Here is a simple idea
```javascript
id: {
  type: 'integer',
  autoIncrement: true
},
name: {
  type: 'string'
},
email: {
  type: 'string',
  unique: true
},
password: {
  type: 'string'
}
```

do we need anything else?

**Comment by rmraya** [comment]
There should be a field that indicates the user status. An inactive user should not be allowed to login or interact with the server.

A uses that has worked in the system should not be deleted, it should be marked as inactive instead.

**Comment by Alino** [comment]
Here is an updated user.

```javascript
id: {
  type: 'integer',
  autoIncrement: true
},
name: {
  type: 'string'
},
email: {
  type: 'string',
  unique: true
},
password: {
  type: 'string'
},
isActive: {
  type: 'boolean'
},
role: {
  type: 'string',
  enum: ['admin', 'basic']
}
```

**Comment by rmraya** [comment]
Roles cannot be an enumeration. They should be open and editable.

Each role should have a number of assignable permissions, like create user, create job, write access to an asset, read-only access, mark a job as completed, download an asset, etc.

**Comment by Alino** [comment]
Based on this user story [User roles](https://github.com/GALAglobal/TAPICC-API-implementation/issues/7)
there are only two roles, admin and basic user. Would you like to expand that user story to make it possible for an admin to create/delete/manage rules for additional roles?

**Comment by rmraya** [comment]
Another item missing in the definition of a user is the organization to which the user belongs.

A job may require a review performed by a linguist from the agency  and a review performed by a client's employee. The agency's linguist should be able to modify the translation, something not allowed to the client's reviewer (client reviewer can leave a comment).

**Comment by rmraya** [comment]
Another reason for having multiple organizations: a project manager from a client can create a job, but only a project manager from the agency can assign tasks and set deadlines.

**Comment by Alino** [comment]
So a user can belong to many organisations?
How should the organisations field be handled, should it be just a string separating the organisations with for example pipe |. Or should we create a new data model / table for organisations and connect them by ids? Do we want to do something else with 'organisations'? Like managing them somehow? I can imagine that an admin could want to rename an organisation for all users and add more meta data about an organisation, therefore it might make more sense to have organisations as a separate table.

**Comment by rmraya** [comment]
A user belongs to one organization.

**Comment by Alino** [comment]
ok, so it can be just a string for each user, right?

id: {
  type: 'integer',
  autoIncrement: true
},
name: {
  type: 'string'
},
email: {
  type: 'string',
  unique: true
},
password: {
  type: 'string'
},
isActive: {
  type: 'boolean'
},
role: {
  type: 'string'
},
organisation: {
  type: 'string'
}

**Comment by rmraya** [comment]
"id" is still listed as an integer.

**Comment by Alino** [comment]
Closing in favour of https://github.com/GALAglobal/TAPICC-API-implementation/issues/24
