### ISSUE TITLE
since the tasks are always related to an asset, shouldn’t the task be a child of the asset then?

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#18]
This is a feedback coming from Yves.

--------

Asset has a “sourceLanguage” field

Task has a “targetLang” field and an “assetId” field

So it seems that:

If we have 1 file to translate and review from EN to DE, we have 1 asset and 1*1*2=2 tasks.
If we have 3 files to translate, review and format from ES to DE and FR, we  have 3 assets and 3*2*3=18 tasks.

In other words:

Job/1/asset/110 (EN)
Job/1/tasks/210 (translate target=DE for asset 110)
Job/1/tasks/210 (review target=DE for asset 110)
Job/1/asset/111 (ES)
Job/1/tasks/211 (translate target=DE for asset 111)
Job/1/tasks/212 (review target=DE for asset 111)
Job/1/tasks/213 (format target=DE for asset 111)
Job/1/tasks/214 (translate target=FR for asset 111)
Job/1/tasks/215 (review target=FR for asset 111)
Job/1/tasks/216 (format target=FR for asset 111)
Job/1/asset/112 (ES)
Job/1/tasks/217 (translate target=DE for asset 112)
Job/1/tasks/218 (review target=DE for asset 112)
Job/1/tasks/219 (format target=DE for asset 112)
Job/1/tasks/220 (translate target=DE for asset 112)
Job/1/tasks/221 (review target=DE for asset 112)
Job/1/tasks/222 (format target=DE for asset 112)
Job/1/asset/113 (ES)
Job/1/tasks/223 (translate target=DE for asset 113)
Etc.

Now, since the tasks are always related to an asset, shouldn’t the task be a child of the asset then?

Job/1/asset/110 (source=EN)
Job/1/asset/110/task/210 (translate target=DE)
Job/1/asset/110/task/211 (review target=DE)
Job/1/asset/111 (source=ES)
Job/1/asset/111/tasks/211 (translate target=DE)
Job/1/asset/111/tasks/212 (review target=DE)
Job/1/asset/111/tasks/213 (format target=DE)
Job/1/asset/111/tasks/214 (translate target=FR)
Job/1/asset/111/tasks/215 (review target=FR)
Job/1/asset/111/tasks/216 (format target=FR)
Etc.

This also means one given job can have multiple source and multiple targets in any combination.

That is a very flexible structure. I’m just wondering how well that maps to existing CAT/TMS systems.

It’s likely that some systems will have to re-organize such job into some kind of groups based on 1 source to N targets. And it means having a way to reference the TAPICC tasks to some objects of the TMS will be needed.

**Comment by Alino** [comment]
I think this is a good idea, this would also make things easier for [Job creation](https://github.com/GALAglobal/TAPICC-API-implementation/issues/20). So that a Job can be created with Assets and the Assets would contain Tasks.

**Comment by nonsequitir** [comment]
In your example ( EN --> FR, ES, DE )  I would point out that in real-world localisation projects, there won't always be a 1-1 relationship between the tasks associated with an asset.  For example, if I choose to MT the source asset for FR, but human translate for ES and DE, then I'd have a Post Edit task associated with FR but an Edit/Proof task for ES & DE. 

By all means, the asset/task relationships could be populated (by default) with similar tasks per asset, but there should be an ability to override this behaviour and the front end of the job creation, rather than having to amend the task lists in the target languages generated.

**Comment by Alino** [comment]
One Asset can have multiple Tasks. You can even have multiple Tasks with same target language but different type of Task.
