### ISSUE TITLE
Server to server communication without user management - proposal

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#24]
There are some uncertainties on how we should handle user management, roles, groups, authentication, user model, gathered information on user, GDPR...

What if we would drop all of that and delegate it to the "external system"?

TAPICC would not have user accounts, but a default system admin account, which would be used by the external system to authenticate into TAPICC. (Other system accounts could be created for other external systems.)

Here is a flowchart for better visualisation

![image](https://user-images.githubusercontent.com/763194/43286524-8a5b9712-9122-11e8-9ab5-7b2f2ca4120b.png)

----

Note: there are some places where we wanted to store user IDs.
For example, _Job.submitter_ or _Task.assignedTo_
These user IDs could be strings which would be filled by the external system and they would represent "_external system name + user ID on that system_"
example: _symfonie.com/43920149320_

This way we would not have collisions between external systems.
TAPICC would not generate user IDs, since it would not care about user management at all.

What do you all think?
Rodolfo, would this approach be acceptable for your use case?

**Comment by Alino** [comment]
To clarify things, the browser would login to symfonie here, not to TAPICC. Browser should never authenticate to TAPICC. This would be just server to server architecture.

**Comment by terales** [comment]
It's perfectly valid for TMS-to-ProZ.com and TMS-to-TMS set of scenarios

**Comment by ysavourel** [comment]
Sounds fine to me.

**Comment by jcompton-moravia** [comment]
After several discussions with WG4 and representatives from other workgroups (on GitHub and through our GtM meetings), it sounds like the consensus is that user management should be de-coupled from TAPICC's primary scope, or at least from Track 1. TAPICC isn't intended to serve as a TMS, supply chain management, or workflow management system, but instead addresses the interaction between such systems within a localization supply chain. User management, in particular, is expected to be brought to the table through whatever system would be acting as the TAPICC host. For example at Moravia we would manage our TAPICC transactions through our Symfonie system for which customer systems and end-users interact. There's no reason that one couldn't create a separate TMS initiative that would use TAPICC to handle fullsome supply chain integration, but that isn't the objective of TAPICC.

**Comment by ysavourel** [comment]
I think not having the management of the users part of TAPICC is fine. And the user ID string proposed by Alex (“external system name + user ID on that system”) is probably good enough.

For this to work we do need to have a specified way to associate the non-TAPICC information with the TAPICC calls.

As it was mentioned last Friday during the call, that is usually done using a token set as the value of a specific field in the header of the REST requests.

The authentication and obtention of the token is done through the application's own mechanism, then all TAPICC calls simply use the token. This allows the TAPICC implementation to associate a customer/user with each call and perform any check for authorization, roles, etc. as needed.

**Comment by Alino** [comment]
I think you are right Yves,

this change to the swagger definition https://github.com/GALAglobal/TAPICC-API-implementation/commit/81dc88249bc6259452ad41a3ede53c41bd44e37f
describes the authentication and enables the swagger UI to authenticate using Authorization Bearer strategy.

I will deploy the actual implementation later in this repo.
