### ISSUE TITLE
proposal: security token addition

### ISSUE THREAD

**Issue by assembledStarDust** [GALAglobal/TAPICC-API-implementation#25]
While I watched the June 29th webinar, there was a question from the audience about security. (no it wasn't me)

Would there be benefit in adding an optional security "token" to the spec? This would be passed from the sink to the source and it would be up to the source application to allow access to assets and processes in a "best practices" way. So from a security viewpoint, there are
two security mechanisms - authentication (by login) and authorization to objects (by security token).

I expect the security token would be part of the login process.

**Comment by Alino** [comment]
By **security token** do you mean a physical device or something like [JSON Web Token](https://en.wikipedia.org/wiki/JSON_Web_Token)?

JSON Web Token is something how I was planning to implement the [authentication](https://github.com/GALAglobal/TAPICC-API-implementation/issues/5).

**Comment by assembledStarDust** [comment]
No, not a physical device. I'll need to remember where I saw it, it was something from google api's, I think. 

Let me find the reference again and get back to you.

**Comment by Alino** [comment]
Closing this, since we will be using api_key as an authentication header. #24
