### ISSUE TITLE
proposal: add version to URL

### ISSUE THREAD

**Issue by assembledStarDust** [GALAglobal/TAPICC-API-implementation#27]
When using REST it seems best practice to add the version id to the url. Example:

/v1/job/{parentid}/task/{id}/downloaddeliverable

Could this be added to the spec.

**Comment by Alino** [comment]
This might make sense later, when there is production ready release of this project and people are using it. Then in next release we would introduce some breaking changes.

Right now, this would add unnecessary development and maintenance burden.

I am including this link for my future reference here -> https://medium.com/@rohitkhatana/handling-api-versioning-with-sailsjs-nodejs-including-blueprints-cec43b406e57

Closing for now.
