### ISSUE TITLE
Inconsistent parameters names for IDs

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#29]
Currently the API documentation uses inconsistent names for some of the ID parameters. For example:

    /job/{id} (id is the ID of the job)
    /job/{parentid}/asset/{id} (parentId is the ID of the job, id is the ID of the asset)

using something like:

    /job/{jobId}
    /job/{jobId}/asset/{assetId}

would be clearer, more consistent and could not be misinterpreted.

**Comment by Alino** [comment]
changed in swagger spec 0.0.6
https://app.swaggerhub.com/apis/Alino/tapicc-api/0.0.6
