### ISSUE TITLE
this project needs testable scenarios

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#3]
using [Gherkin syntax](https://docs.cucumber.io/gherkin/reference/)

**Comment by terales** [comment]
Nice work, @Alino!
Do you have a list of scenarios to test?
Can you implement one test of scenario so I could follow up with others?

**Comment by Alino** [comment]
Thanks @terales 
I don't have a list of scenarios, but anyone is welcome to write them. I would be happy to implement them. We should maybe focus first on the business critical logic scenarios.
I think that the scenarios should be written together with user stories, the scenarios should serve as acceptance tests.

--------
here is an example:
User story description:
_As a user I wanna register an account so that I can use TAPICC api methods as an authenticated user._

Scenario:
_Given that no user is authenticated
When a request to '/register' is made with this data '{ username: "someone", password: "secret" }'
Then a new user with name "someone" is added to the database_

------
Example 2:
_As a user I wanna login so that I can use TAPICC api methods as an authenticated user._

Scenario - successful login:
_Given that the user "someone" with password "secret" exists.
When a request to '/login' is made with this data '{ username" someone", password: "secret" }'
Then the server responds with the authentication token_

Scenario - wrong password:
_Given that the user "someone" with password "secret" exists.
When a request to '/login' is made with this data '{ username" someone", password: "wrongPAss" }'
Then the server responds with an error_

**Comment by Alino** [comment]
I think we should have meetings where we will plan user stories, discuss them in detail and write acceptance tests (scenarios) together.

**Comment by terales** [comment]
Totally agree with you!
Please, invite me to such meeting or ping me if you would have anything to implement.

**Comment by rmraya** [comment]
Users should not be allowed to create their own account. An administrator should add them to the system.
