### ISSUE TITLE
Asset References - proposal

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#32]
I propose to create new data model called ```Reference```

```javascript
{
  id: {
    type: 'integer'
  },
  assetId: {
    model: 'asset'
  },
  description: {
    type: 'string',
    example: 'Translation Memory'
  },
  file: {
     type: 'binary'
  },
  url: {
    type: 'string'
  }
}
```

endpoints:
```POST /asset/{parentId}/reference/uploadfile```
```GET, PUT, DELETE /reference/{id}```

----

example - seeing an Asset and being able to view it's References:

```GET /job/1/asset/5```

response:

```javascript
{
  id: 5,
  sourceLanguage: 'en'
  jobId: 1,
  tasks: [{ id: 14, targetLanguage: 'sk', type: 'translation' }],
  references: [
    { id: 23, assetId: 5, description: 'Translation Memory' },
    { id: 24, assetId: 5, description: 'Termbase' }
  ]
}
```

----

Note:
- this would mean that _Asset.isReference_ will be removed.
- this would be good separation of concerns between Assets and References
- this would link References with Assets, so that you can also download all files related to an Asset

Questions:
1. Do we want many to many relationship between Assets and References? Therefore one Reference could be used in multiple Assets.

**Comment by assembledStarDust** [comment]
There may also be benefit in adding to the asset itself -

Asset.type

here may be benefit in seperating out source file types, downloadableDeliverables, uploadableDeliverables, Devliverables, reference when creating assets.


Asset.Description

I see in the proposal for reference there is description - this should also be applied to the parent asset itself.

**Comment by Alino** [comment]
If we implement this References proposal, then Asset.type won't make much sense to me.

Asset.file = the source file of the Asset (an Asset is always an Asset)
Reference.file = the reference file (the Reference is always a Reference)
Task.file = the deliverable (Task is always Task)

----

I agree with Asset.description addition.

**Comment by assembledStarDust** [comment]
So if I'm understanding this right, any file uploaded or downloaded is *not* an asset. Asset is a term for source files. Separation of file type as I propose is already done in the structure.  Do I have that right?

**Comment by Alino** [comment]
closing in favour of https://github.com/GALAglobal/TAPICC-API-implementation/issues/58
