### ISSUE TITLE
search parameters

### ISSUE THREAD

**Issue by assembledStarDust** [GALAglobal/TAPICC-API-implementation#35]
Running the thought exercise of discovering a job and the tasks, to downloading a payload, it seems the process might be.

discover jobs. `GET /job`
discover tasks of job `GET /job/{id}/task`
download payload *(as asset*) as detailed in task `GET /asset/{parentid}/task/{id}/downloaddeliverable`

In the discovery of objects, would there be benefit in allowing search parameters, to pull back only what is required.

An example search maybe return all /job with tasks of type "translation" with targetLanguage of "fr-FR".

Is this already detailed somewhere?

**Comment by Alino** [comment]
Actually sails.js framework supports this search (even sort) functionality [out of the box](https://sailsjs.com/documentation/reference/blueprint-api/find-where).

Maybe we should mention this in our swagger definition or other documentation, to make it part of the TAPICC standard.

----

for example this curl request

```shell
curl -X GET "http://localhost:1337/assets?sourceLanguage=en" -H "accept: application/json" -H "Authorization: Bearer 111"
```

should filter all Assets where sourceLanguage is equal to "en"

**Comment by Alino** [comment]
we will include information how to do this in prose deliverables.
