### ISSUE TITLE
Supporting virtual assets

### ISSUE THREAD

**Issue by jcompton-moravia** [GALAglobal/TAPICC-API-implementation#50]
Right now our data model is based around the idea of an asset being a parent of tasks. One piece of content that needs to be translated into ten languages would contain ten translation tasks that would create ten deliverables. Currently, a task cannot exist without a corresponding asset.

This makes sense when the content itself is actually being transported around, but what about situations where the localization process (human linguist or process) needs to _come to the content_. That is, instead of sending around content to be transformed, the worker (or process) needs to do this work within a different ecosystem.

This is really a common scenario for us at Moravia, for example when we're performing LQA work and all the content already lives on another system. In this scenario, we might be creating a report deliverable from content that's being rendered online.

If we want to keep the model whereby a Task is a child of an Asset, should we allow that an asset can be a URL as opposed to a "payload" of content?

What do folks think?

**Comment by Alino** [comment]
Seems like related or duplicate with
https://github.com/GALAglobal/TAPICC-API-implementation/issues/47
and 
https://github.com/GALAglobal/TAPICC-API-implementation/issues/49
