### ISSUE TITLE
api_key in parameter

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#51]
The TAPICC-API-Implementation readme says:

> An alternative is to use the api_key in URL query param ?api_key={api_key} (this is useful, when you want to try the API in the browser)

Is this an extension of that specific implementation?
Or is it part of the TAPICC specification?

**Comment by Alino** [comment]
Good question. I think it doesn't have to be part of TAPICC specification. But it is something nice to have, especially during testing and development.
