### ISSUE TITLE
Return for creation

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#54]
Usually REST APIs return 201 (Created) and the created object when one create a new resource. Currently the API returns 200 with the created job, task, asset or webhook. We should return 201.

**Comment by ysavourel** [comment]
It seems [the stackoverflow discussion](https://stackoverflow.com/questions/1860645/create-request-with-post-which-response-codes-200-or-201-and-content) is about how to indicate the resource(s) created, rather than choosing between 200 and 201. And for that we should certainly use the Location entry header.

There is certainly nothing particularly wrong with 200. But it seems to me that if there is an HTTP response code specifically designated to indicate a resource has been created, we should use it. Nothing in its definition say it should be used when the resource is not attached (and 200 when the resource is attached).

201 after creation is what some recommend:
- https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#post-methods,
- or https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201.

And it is what some TMS already use:
- XTM: https://www.xtm-cloud.com/rest-api/#operation/createProjectUsingPOST
- MemSource : https://cloud.memsource.com/web/docs/api#operation/createClient

**Comment by Alino** [comment]
updated in swagger https://github.com/GALAglobal/TAPICC-API-implementation/commit/17048737e981975ee704c94ddd4eac191209ded9
