### ISSUE TITLE
Return for deletion

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#55]
Currently a successful call to DELETE returns the resource and 200. That is an option.

But usually it's a lot easier for the implementation to return 204 (NoContent) with no resource at all on success. After all: it has been deleted.

It can also return 202 (Accepted) with the resource if the deletion request has been accepted by the server, but not done yet (if it's in a queue for example).

**Comment by Alino** [comment]
updated in swagger https://github.com/GALAglobal/TAPICC-API-implementation/commit/3ab715f157c617de707ff392214e2732641acc0c
