### ISSUE TITLE
Tasks for a project

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#56]
Now that tasks are decoupled from assets (per issue #47), it's not clear how we can access tasks .

- Obviously there is `GET /tasks` but that gives you all the tasks across all jobs, I'm not sure anyone would want to get that list (and it could get rather long).
- There is the `tasks` list in each asset object, but that won't account for task not associated to an asset.

I suppose we could have `GET /tasks?jobId={jobId}` but currently it's not defined.
Should we have `GET /jobs/{jobId}/tasks`?

**Comment by Alino** [comment]
I would prefer to have one universal way how to filter collections based on it's parameters, and that is as you mentioned:
>I suppose we could have GET /tasks?jobId={jobId} but currently it's not defined.

This is related to https://github.com/GALAglobal/TAPICC-API-implementation/issues/35

Unfortunately it seems there is [no way currently to define global query parameters](https://github.com/OAI/OpenAPI-Specification/issues/445) in swagger definition. We would have to add them manually to each route.
So I wonder if we should do it in swagger definition (add all possible query params for filtering and sorting in each route) Or have some single declaration in some external documentation.
