### ISSUE TITLE
Proposal: add Financial Info object

### ISSUE THREAD

**Issue by assembledStarDust** [GALAglobal/TAPICC-API-implementation#59]
Folks expect to be paid for the work they do. I'd propose a financial object to be added to task (and possibly job) objects to manage transfer of commercial financial information. 

Why a separate object - this is so that oauth2 scopes can limit who can see potentially commercially sensitive financial information.

The structure of such an object may include CAT model info and other pricing information. To be determined.

**Comment by Alino** [comment]
what would the object look like? Is this something we would define as a standard, or could this object be different from implementation to implementation?

**Comment by assembledStarDust** [comment]
propose the following object


![financial](https://user-images.githubusercontent.com/41793450/52963143-ee70ed80-3396-11e9-8b0e-8d0ed15dfdbe.png)


[
{"uid":"identifier","ref":"reference","desc":"description","metric":[{"UOM":"words"},{"100%":"0","99-95%":"0","94%-85%":"0","84%-75%":"0","ICE":"0","no-Match":"0","total":"0"}],"rate":[{"currency":"currency"},{"100%":"0.00","99-95%":"0.00","94%-85%":"0.00","84%-75%":"0.00","ICE":"0.00","no-Match":"0.00","total":"0.00"}],"financial":[{"currency":"currency"},{"100%":"0.00","99-95%":"0.00","94%-85%":"0.00","84%-75%":"0.00","ICE":"0.00","no-Match":"0.00","total":"0.00"}]}
]

uid - unique id for the object
ref - user references, like file path and file name.
description - some longer description for the resource.
metric - this is made up of two objects - the Units Of Measure and the range of items of measure. These could be the CAT model of words, or hours of labour or whatever. 
rate - this is the rate of how much each UOM is costed at.
financial. This is how much it costs for this resource.

**Comment by terales** [comment]
It's already a February and we don't have a completed API spec, sample implementation and prose deliverable yet.

Let's try to keep the scope as close as possible to what we already have and add new ideas for the second revision/version of API. 

Right now financial info could be transferred as a file inside Input or Deliverable. It's not the best possible way, but we are not restricting companies to exchange financial info with API, just trying to avoid fuzzy parts.

**Comment by assembledStarDust** [comment]
financial info should be separate. ok to leave as task type scoping.

this issue can be closed.
