### ISSUE TITLE
Proposal: add UserData object

### ISSUE THREAD

**Issue by assembledStarDust** [GALAglobal/TAPICC-API-implementation#60]
While there is information being passed via the WG4 spec, there may be instances where it is not enough, or there is something forgotten. 

I'd propose a user data object to be added to job and task objects, or perhaps a field or (shudder) an array added to job and task objects.

This is so that there is flexibility for users to add info that is not contained within the original spec.

I'd propose object, as it could be retrieved by endpoint and less likely to break the core spec.

**Comment by Alino** [comment]
So the properties of the user object would be declared by the implementors? Therefore inconsistent from implementation to implementation?

**Comment by terales** [comment]
We've already discussed this idea in WH1. The decision was to put whatever you have into input as a file.

**Comment by Alino** [comment]
So can this be closed, is there nothing actionable?
