### ISSUE TITLE
Remove "commands" from file actions - proposal

### ISSUE THREAD

**Issue by mesztam** [GALAglobal/TAPICC-API-implementation#62]
To conform better to REST principles, I would suggest replacing/removing the imperative file actions from the following endpoints:

`POST /tasks/{taskId}/uploaddeliverable` => `POST /tasks/{taskId}/deliverable`
`GET /tasks/{taskId}/downloaddeliverable` => `GET /tasks/{taskId}/deliverable`

similarly:
`POST /jobs/{jobId}/assets/uploadfile` => `POST /jobs/{jobId}/assets` , I think we don't need the `uploadfile` suffix, since we are actually creating an asset, where the file itself is just a parameter

`GET /jobs/{jobId}/assets/{assetId}/downloadfile` => `GET /jobs/{jobId}/assets/{assetId}/file` => since we are accessing the "file" related to the asset specified by its id

**Comment by Alino** [comment]
changed in swagger https://github.com/GALAglobal/TAPICC-API-implementation/commit/0e61cc44da450119cbe2746a3bcc20d0ace1295b
