### ISSUE TITLE
We should add a set of endpoints to TAPICC to support import/export of TIPP v2

### ISSUE THREAD

**Issue by jcompton-moravia** [GALAglobal/TAPICC-API-implementation#63]
In order to harmonize TAPICC with TIPP, the standardized "localization package" format for non-API interactions between actors in a localization supply chain, I propose that we add endpoints to TAPICC to support the generation of and consumption of (parsing and conversion to TAPICC data objects) of TIPP packages.

This would enable that a TAPICC host be able to support interactions where the "consumer" wasn't a system, for example, but a person using a portal to receive and deliver work. 

Reference of TIPP 2 lives here:

http://www.linport.org/
https://github.com/translationcommons/TIPPv2
https://github.com/translationcommons/TIPPv2/blob/master/The_TMS_Interoperability_Protocol_Package-2.0-draft.pdf

**Comment by Alino** [comment]
Let me share my notes with you:
Here is something about the TIPP structure

![image](https://user-images.githubusercontent.com/763194/61314361-c201b600-a7fc-11e9-9f92-be26a79786ef.png)

So TIPP is a zip file.
We need to support import / export of TIPP.
So I guess we need just two endpoints.

Something like
```GET /TIPP``` (to export/download a TIPP package)
```POST /TIPP``` (to upload/import a TIPP package)

Next we need to specify the required and optional params for each request. But to be able to do this, we need to understand TIPP better. I can dive into the TIPP draft later. If anyone knows already what we need, please tell us :)

**Comment by Alino** [comment]
I made a quick look again at the draft and it looks to me that all we need is just to specify which Task we want to export.

example:
create a TIPP package and include a Task with id 11

```GET /TIPP/?taskId=11```

---

If a TAPICC Task is associated with a reference and this Task is being exported as a part of TIPP package, all its references should be included.

---

I think for importing TIPP to TAPICC we don't need any params. All information is available inside the zip and a TAPICC Task can be created from it.

---

**Please let me know if I missed something.**

---
It will not be easy for implementers to implement TIPP endpoints. Not rocket science either, but definitely a slow down as it is another spec. they will have to read/understand and implement valid solution, file/folder structure, generating manifest file and conversion... Hopefully it won't negatively affect adaptation. Perhaps it could be optional in terms of TAPICC compliance. Just my thought.

**Comment by Alino** [comment]
added in swagger https://github.com/GALAglobal/TAPICC-API-implementation/commit/c1313a79b199b0ccfaecab31d67ce3f4c49c43a1

**Comment by terales** [comment]
@Alino for me harmonizing with TIPP means that we want to have our responses, structure and terminology aligned with TIPP package for Job (Project in TIPP), tasks and assets (Resources in TIPP).

I can take a closer look on inconsistencies on February, if needed.
