### ISSUE TITLE
POST and PUT for Tasks have only one inputId

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#64]
The parameters for POST and PUT tasks have show only one inputId field instead of an array.
A task can have several inputs, we should probably have an array of inputIds in the PUT and POST parameters too.

**Comment by Alino** [comment]
correct, I think only the examples were outdated. Fixed https://github.com/GALAglobal/TAPICC-API-implementation/commit/adbd4bc351b54cadbfb9fae38e7f7bc38a81fb30
