### ISSUE TITLE
Enums should be more consistent and code friendly

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#68]
We have several list of string values, described as "enums" in the specification:
- Task type
- Task status
- File type
- etc.

Currently many of the values are not very code friendly, for example they have spaces like "Review with LQA", etc.

I would propose that we have them all consistent:
- in lowercase
- using minus to separate the different parts of the label

For example: "review-with-lqa". "in-progress", etc.

**Comment by Alino** [comment]
I agree with this proposal. Changed the swagger file
https://github.com/GALAglobal/TAPICC-API-implementation/commit/01750ea9995dcad72e029fc325d3977b390ca2a1
