### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC-API-implementation#7]
As a product manager, I wanna implement following user roles

- admin
  - can manage groups and users
- basic user
  - can perform API requests

**Comment by Alino** [comment]
can an admin, create/delete more roles?

**Comment by rmraya** [comment]
User groups and roles are two different things.

User groups are important for assigning tasks.

**Comment by Alino** [comment]
ok, so we will manage all permissions with roles, therefore an admin must be able to:
- create and delete new roles
- assign roles to other users.
- manage a list of permissions per role.

**Comment by Alino** [comment]
Closing in favour of https://github.com/GALAglobal/TAPICC-API-implementation/issues/24
