### ISSUE TITLE
Input vs Input IDs in Job

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#71]
Is there a string reason to have the list of its Input objects in given Job object as it is the case in the current Swagger API? (https://app.swaggerhub.com/apis/Alino/tapicc-api/0.0.7#/job)

In the other objects we use lists of IDs rather than the objects themselves.

**Comment by Alino** [comment]
good question, perhaps we should unify this, and all objects should return only themselves and not children directly but only list of ids.
If no one objects to this in next week, I think we can change this.

**Comment by Alino** [comment]
changed https://github.com/GALAglobal/TAPICC-API-implementation/commit/f8c9fb78c2dc2fffc72ed20bb2199f0cb8047986
